import type { MenuItem, MealTime } from '../types';

const createMenu = (id: number, brand: string, name: string, type: MenuItem['type']): MenuItem => ({
  id,
  brand,
  name,
  type
});

export const MENUS: Record<MealTime, MenuItem[]> = {
  lunch: [
    createMenu(1, "버거킹", "통새우 와퍼 세트", "burger"),
    createMenu(2, "맥도날드", "빅맥 세트", "burger"),
    createMenu(3, "맥도날드", "베이컨 토마토 디럭스", "burger"),
    createMenu(4, "맥도날드", "상하이 버거 세트", "burger"),
    createMenu(5, "롯데리아", "한우 불고기 버거", "burger"),
    createMenu(6, "롯데리아", "새우버거 세트", "burger"),
    createMenu(7, "맘스터치", "싸이버거 세트", "burger"),
    createMenu(8, "맘스터치", "인크레더블 버거", "burger"),
    createMenu(9, "프랭크버거", "치즈버거 세트", "burger"),
    createMenu(10, "쉐이크쉑", "쉑버거 & 프라이", "burger"),
    createMenu(11, "노브랜드버거", "NBB 시그니처", "burger"),
    createMenu(12, "KFC", "징거버거 세트", "burger"),
    createMenu(13, "서브웨이", "이탈리안 비엠티 15cm", "sandwich"),
    createMenu(14, "서브웨이", "에그마요 15cm", "sandwich"),
    createMenu(15, "서브웨이", "스테이크 & 치즈", "sandwich"),
    createMenu(16, "서브웨이", "로스트 치킨", "sandwich"),
    createMenu(17, "퀴즈노스", "트레디셔널", "sandwich"),
    createMenu(18, "이삭토스트", "햄치즈 스페셜", "sandwich"),
    createMenu(19, "이삭토스트", "베이컨 베스트", "sandwich"),
    createMenu(20, "에그드랍", "미스터 에그", "sandwich"),
    createMenu(21, "에그드랍", "아메리칸 햄 치즈", "sandwich"),
    createMenu(22, "본죽", "낙지 김치 죽", "korean"),
    createMenu(23, "본죽", "전복죽", "korean"),
    createMenu(24, "본죽", "쇠고기 야채죽", "korean"),
    createMenu(25, "본죽&비빔밥", "돌솥 비빔밥", "korean"),
    createMenu(26, "한솥도시락", "치킨마요", "korean"),
    createMenu(27, "한솥도시락", "도련님 도시락", "korean"),
    createMenu(28, "한솥도시락", "돈까스 도련님", "korean"),
    createMenu(29, "김가네", "라볶이 & 김밥", "korean"),
    createMenu(30, "고봉민김밥", "돈가스 김밥", "korean"),
    createMenu(31, "고봉민김밥", "참치 김밥", "korean"),
    createMenu(32, "바르다김선생", "크림치즈 호두 김밥", "korean"),
    createMenu(33, "싸움의고수", "1인 보쌈 M", "korean"),
    createMenu(34, "싸움의고수", "1인 삼겹살 M", "korean"),
    createMenu(35, "국수나무", "생면국수 & 치즈돈가스", "korean"),
    createMenu(36, "미정국수", "멸치국수", "korean"),
    createMenu(37, "역전우동", "옛날우동 & 명란미니덮밥", "korean"),
    createMenu(38, "홍콩반점0410", "짬뽕 & 탕수육 소", "korean"),
    createMenu(39, "홍콩반점0410", "짜장면", "korean"),
    createMenu(40, "홍콩반점0410", "쟁반짜장", "korean"),
    createMenu(41, "샐러디", "칠리베이컨 웜볼", "sandwich"),
    createMenu(42, "샐러디", "우삼겹 웜볼", "sandwich"),
    createMenu(43, "포케올데이", "현미밥 포케", "sandwich"),
    createMenu(44, "파리바게뜨", "런치 샌드위치", "sandwich"),
    createMenu(45, "뚜레쥬르", "BELT 샌드위치", "sandwich"),
    createMenu(46, "스타벅스", "바비큐 치킨 치즈 치아바타", "sandwich"),
    createMenu(47, "이디야", "페퍼로니 피자 샌드위치", "sandwich"),
    createMenu(48, "육대장", "옛날 육개장", "stew"),
    createMenu(49, "이화수전통육개장", "차돌 육개장", "stew"),
    createMenu(50, "놀부부대찌개", "부대찌개 1인", "stew"),
    createMenu(51, "채선당", "샤브샤브 점심특선", "stew"),
    createMenu(52, "담소소사골순대", "순대국", "stew"),
    createMenu(53, "무봉리토종순대국", "순대국", "stew"),
    createMenu(54, "할매순대국", "얼큰 순대국", "stew"),
    createMenu(55, "신의주찹쌀순대", "순대국 정식", "stew"),
    createMenu(56, "북창동순두부", "해물 순두부", "stew"),
    createMenu(57, "강창구찹쌀진순대", "진순대국", "stew"),
    createMenu(58, "미소야", "로스카츠 정식", "korean"),
    createMenu(59, "미소야", "알밥 정식", "korean"),
    createMenu(60, "사보텐", "모짜렐라 치즈 카츠", "korean"),
    createMenu(61, "코코이찌방야", "비프 카레", "korean"),
    createMenu(62, "아비꼬", "허브치킨 카레", "korean"),
    createMenu(63, "김밥천국", "스페셜 정식", "korean"),
    createMenu(64, "김밥천국", "철판 김치 볶음밥", "korean"),
    createMenu(65, "버거킹", "콰트로 치즈 와퍼", "burger"),
    createMenu(66, "버거킹", "몬스터 와퍼", "burger"),
    createMenu(67, "맥도날드", "슈비버거", "burger"),
    createMenu(68, "맥도날드", "맥스파이시 상하이 버거", "burger"),
    createMenu(69, "롯데리아", "T-Rex 버거", "burger"),
    createMenu(70, "롯데리아", "핫크리스피 버거", "burger"),
    createMenu(71, "맘스터치", "딥치즈 버거", "burger"),
    createMenu(72, "맘스터치", "화이트갈릭 버거", "burger"),
    createMenu(73, "써브웨이", "치킨 데리야끼", "sandwich"),
    createMenu(74, "써브웨이", "스파이시 이탈리안", "sandwich"),
    createMenu(75, "써브웨이", "터키 샌드위치", "sandwich"),
    createMenu(76, "이삭토스트", "딥치즈 베이컨", "sandwich"),
    createMenu(77, "에그드랍", "갈릭 베이컨 치즈", "sandwich"),
    createMenu(78, "봉구스밥버거", "햄치즈 밥버거", "korean"),
    createMenu(79, "봉구스밥버거", "치킨마요 밥버거", "korean"),
    createMenu(80, "지지고", "나이스 라이스", "korean"),
    createMenu(81, "죠스떡볶이", "1인 세트", "korean"),
    createMenu(82, "신전떡볶이", "치즈 떡볶이 & 컵밥", "korean"),
    createMenu(83, "청년다방", "버터갈릭 감자튀김 & 떡볶이", "korean"),
    createMenu(84, "엽기떡볶이", "2인 엽떡", "korean"),
    createMenu(85, "유가네닭갈비", "닭갈비 볶음밥", "korean"),
    createMenu(86, "역전우동", "매운모둠어묵우동", "korean"),
    createMenu(87, "역전우동", "냉모밀", "korean"),
    createMenu(88, "미정국수", "제육덮밥", "korean"),
    createMenu(89, "홍콩반점", "군만두 & 짬뽕밥", "korean"),
    createMenu(90, "교동짬뽕", "교동짬뽕", "korean"),
    createMenu(91, "이비가짬뽕", "이비가 짬뽕", "korean"),
    createMenu(92, "현대옥", "콩나물 국밥", "stew"),
    createMenu(93, "콩심", "콩나물 국밥", "stew"),
    createMenu(94, "백종원의 원조쌈밥", "대패삼겹 쌈밥", "korean"),
    createMenu(95, "새마을식당", "7분 돼지김치", "korean"),
    createMenu(96, "롤링파스타", "토마토 파스타", "korean"),
    createMenu(97, "롤링파스타", "알리오 올리오", "korean"),
    createMenu(98, "온기정", "텐동", "korean"),
    createMenu(99, "토끼정", "크림 카레 우동", "korean"),
    createMenu(100, "서가앤쿡", "목살 필라프", "korean"),
  ],
  dinner: [
    createMenu(1, "하남돼지집", "삼겹살 & 명이나물", "meat"),
    createMenu(2, "하남돼지집", "모둠 한판", "meat"),
    createMenu(3, "맛찬들왕소금구이", "숙성 삼겹살", "meat"),
    createMenu(4, "맛찬들왕소금구이", "숙성 목살", "meat"),
    createMenu(5, "새마을식당", "열탄불고기", "meat"),
    createMenu(6, "이차돌", "차돌박이 & 돌초밥", "meat"),
    createMenu(7, "명륜진사갈비", "돼지갈비 무한리필", "meat"),
    createMenu(8, "아웃백", "투움바 파스타", "korean"),
    createMenu(9, "아웃백", "베이비 백 립", "meat"),
    createMenu(10, "아웃백", "토마호크 스테이크", "meat"),
    createMenu(11, "빕스(VIPS)", "샐러드바 & 스테이크", "meat"),
    createMenu(12, "애슐리퀸즈", "월드 고메 뷔페", "korean"),
    createMenu(13, "매드포갈릭", "갈릭 스노잉 피자", "pizza"),
    createMenu(14, "매드포갈릭", "갈릭 스테이크", "meat"),
    createMenu(15, "서가앤쿡", "목살 한상", "meat"),
    createMenu(16, "롤링파스타", "매운 크림 파스타", "korean"),
    createMenu(17, "원할머니보쌈", "모둠보쌈", "korean"),
    createMenu(18, "원할머니보쌈", "맛보쌈", "korean"),
    createMenu(19, "놀부보쌈", "보쌈 김치 세트", "korean"),
    createMenu(20, "놀부부대찌개", "놀부 부대찌개", "stew"),
    createMenu(21, "가장맛있는족발", "반반 족발", "korean"),
    createMenu(22, "가장맛있는족발", "직화 불족발", "korean"),
    createMenu(23, "마왕족발", "마왕 통구이", "korean"),
    createMenu(24, "죠스떡볶이", "떡튀순 세트", "korean"),
    createMenu(25, "청년다방", "차돌 떡볶이", "korean"),
    createMenu(26, "청년다방", "통오징어 떡볶이", "korean"),
    createMenu(27, "두끼", "즉석 떡볶이 무한리필", "korean"),
    createMenu(28, "동대문엽기떡볶이", "엽기 닭볶음탕", "stew"),
    createMenu(29, "유가네닭갈비", "치즈 닭갈비", "meat"),
    createMenu(30, "5.5닭갈비", "춘천 닭갈비", "meat"),
    createMenu(31, "홍대개미", "스테이크 덮밥", "korean"),
    createMenu(32, "홍대개미", "연어 덮밥", "korean"),
    createMenu(33, "도미노피자", "블랙타이거 슈림프", "pizza"),
    createMenu(34, "도미노피자", "포테이토 피자", "pizza"),
    createMenu(35, "도미노피자", "리얼 불고기 피자", "pizza"),
    createMenu(36, "피자헛", "리치골드 치즈킹", "pizza"),
    createMenu(37, "피자헛", "티본스테이크 피자", "pizza"),
    createMenu(38, "파파존스", "수퍼 파파스", "pizza"),
    createMenu(39, "파파존스", "아이리쉬 포테이토", "pizza"),
    createMenu(40, "피자스쿨", "고구마 피자", "pizza"),
    createMenu(41, "피자스쿨", "깐쇼새우 피자", "pizza"),
    createMenu(42, "반올림피자", "내맘대로 4가지", "pizza"),
    createMenu(43, "미스터피자", "쉬림프 골드", "pizza"),
    createMenu(44, "교촌치킨", "허니 콤보", "chicken"),
    createMenu(45, "교촌치킨", "레드 콤보", "chicken"),
    createMenu(46, "BHC", "뿌링클", "chicken"),
    createMenu(47, "BHC", "맛초킹", "chicken"),
    createMenu(48, "BHC", "골드킹", "chicken"),
    createMenu(49, "BBQ", "황금올리브 치킨", "chicken"),
    createMenu(50, "BBQ", "자마이카 통다리", "chicken"),
    createMenu(51, "굽네치킨", "고추바사삭", "chicken"),
    createMenu(52, "굽네치킨", "볼케이노", "chicken"),
    createMenu(53, "푸라닭", "블랙알리오", "chicken"),
    createMenu(54, "푸라닭", "고추마요", "chicken"),
    createMenu(55, "60계치킨", "간지치킨", "chicken"),
    createMenu(56, "60계치킨", "고추치킨", "chicken"),
    createMenu(57, "노랑통닭", "순살 3종 세트", "chicken"),
    createMenu(58, "노랑통닭", "알싸한 마늘 치킨", "chicken"),
    createMenu(59, "자담치킨", "맵슐랭", "chicken"),
    createMenu(60, "네네치킨", "오리엔탈 파닭", "chicken"),
    createMenu(61, "네네치킨", "스노윙 치킨", "chicken"),
    createMenu(62, "처갓집양념치킨", "슈프림 양념치킨", "chicken"),
    createMenu(63, "호식이두마리치킨", "간장 + 양념", "chicken"),
    createMenu(64, "페리카나", "양념치킨", "chicken"),
    createMenu(65, "멕시카나", "땡초치킨", "chicken"),
    createMenu(66, "또래오래", "갈릭반 핫양념반", "chicken"),
    createMenu(67, "지코바", "숯불 양념 치킨", "chicken"),
    createMenu(68, "쿠우쿠우", "초밥 뷔페", "korean"),
    createMenu(69, "스시로", "회전 초밥", "korean"),
    createMenu(70, "갓파스시", "무제한 초밥", "korean"),
    createMenu(71, "은행골", "도로 초밥", "korean"),
    createMenu(72, "상무초밥", "특선 초밥", "korean"),
    createMenu(73, "곱창고", "곱창 모둠", "meat"),
    createMenu(74, "곱창이야기", "소곱창 구이", "meat"),
    createMenu(75, "대한곱창", "불쇼 모둠 곱창", "meat"),
    createMenu(76, "세광양대창", "대창 구이", "meat"),
    createMenu(77, "오발탄", "특양 구이", "meat"),
    createMenu(78, "연타발", "양대창 구이", "meat"),
    createMenu(79, "교대이층집", "꽃삼겹", "meat"),
    createMenu(80, "금돼지식당", "본삼겹", "meat"),
    createMenu(81, "숙성도", "흑돼지 구이", "meat"),
    createMenu(82, "엉터리생고기", "삼겹살 무한리필", "meat"),
    createMenu(83, "육회지존", "한우 육회", "meat"),
    createMenu(84, "육회관", "육사시미", "meat"),
    createMenu(85, "백억하누", "전복 삼합", "meat"),
    createMenu(86, "창고43", "한우 등심", "meat"),
    createMenu(87, "대도식당", "한우 등심", "meat"),
    createMenu(88, "새벽집", "육회 비빔밥", "korean"),
    createMenu(89, "봉피양", "돼지갈비 & 평양냉면", "meat"),
    createMenu(90, "을밀대", "평양냉면 & 수육", "korean"),
    createMenu(91, "우래옥", "불고기 & 냉면", "meat"),
    createMenu(92, "필동면옥", "제육 & 냉면", "meat"),
    createMenu(93, "강남면옥", "갈비찜", "meat"),
    createMenu(94, "개성손만두", "만두전골", "stew"),
    createMenu(95, "등촌샤브칼국수", "버섯 칼국수", "stew"),
    createMenu(96, "바르미샤브샤브", "쇠고기 샤브샤브", "stew"),
    createMenu(97, "로운샤브샤브", "무제한 샤브샤브", "stew"),
    createMenu(98, "편편집", "편백찜 & 샤브샤브", "stew"),
    createMenu(99, "소담촌", "월남쌈 & 샤브샤브", "stew"),
    createMenu(100, "꽃마름", "월남쌈 샤브샤브", "stew"),
  ],
  latenight: [
    createMenu(1, "엽기떡볶이", "엽기 떡볶이 (오리지널)", "korean"),
    createMenu(2, "엽기떡볶이", "로제 떡볶이", "korean"),
    createMenu(3, "엽기떡볶이", "마라 떡볶이", "korean"),
    createMenu(4, "신전떡볶이", "치즈 떡볶이 & 오뎅튀김", "korean"),
    createMenu(5, "배떡", "로제 떡볶이", "korean"),
    createMenu(6, "응급실떡볶이", "응급실 국물 떡볶이", "korean"),
    createMenu(7, "삼첩분식", "마라 로제 떡볶이", "korean"),
    createMenu(8, "삼첩분식", "바질 크림 떡볶이", "korean"),
    createMenu(9, "한신포차", "국물 닭발", "pub"),
    createMenu(10, "한신포차", "오돌뼈 & 주먹밥", "pub"),
    createMenu(11, "한신포차", "통닭", "pub"),
    createMenu(12, "역전할머니맥주", "짜파구리 & 맥주", "pub"),
    createMenu(13, "역전할머니맥주", "갈릭 빠다 포테이토", "pub"),
    createMenu(14, "역전할머니맥주", "살얼음 맥주", "pub"),
    createMenu(15, "역전할머니맥주", "치즈 라볶이", "pub"),
    createMenu(16, "크라운호프", "우유튀김 & 맥주", "pub"),
    createMenu(17, "크라운호프", "페퍼로니 피자", "pub"),
    createMenu(18, "투다리", "김치우동", "pub"),
    createMenu(19, "투다리", "팽이버섯 말이", "pub"),
    createMenu(20, "투다리", "모둠 꼬치", "pub"),
    createMenu(21, "용구비어", "크림 생맥주", "pub"),
    createMenu(22, "봉구비어", "감자튀김 & 치즈스틱", "pub"),
    createMenu(23, "교촌치킨", "레드 콤보", "chicken"),
    createMenu(24, "교촌치킨", "허니 콤보", "chicken"),
    createMenu(25, "BBQ", "자마이카 통다리", "chicken"),
    createMenu(26, "BBQ", "황금올리브 속안심", "chicken"),
    createMenu(27, "BHC", "맛초킹", "chicken"),
    createMenu(28, "BHC", "뿌링클 콤보", "chicken"),
    createMenu(29, "호식이두마리치킨", "간장 & 양념 세트", "chicken"),
    createMenu(30, "페리카나", "반반 치킨", "chicken"),
    createMenu(31, "멕시카나", "땡초 치킨", "chicken"),
    createMenu(32, "또래오래", "갈릭반 핫양념반", "chicken"),
    createMenu(33, "지코바", "숯불 양념 치킨", "chicken"),
    createMenu(34, "지코바", "숯불 소금 구이", "chicken"),
    createMenu(35, "훌랄라치킨", "참숯 바베큐", "chicken"),
    createMenu(36, "피자나라치킨공주", "피치 세트", "pizza"),
    createMenu(37, "만족오향족발", "냉채 족발", "korean"),
    createMenu(38, "만족오향족발", "반반 족발", "korean"),
    createMenu(39, "원할머니보쌈", "매운 불족발", "korean"),
    createMenu(40, "육회지존", "한우 육회", "pub"),
    createMenu(41, "육회관", "육사시미", "pub"),
    createMenu(42, "곱창이야기", "소곱창 구이", "pub"),
    createMenu(43, "대한곱창", "불쇼 모둠 곱창", "pub"),
    createMenu(44, "GS25", "오모리 김치찌개 라면", "korean"),
    createMenu(45, "GS25", "공화춘 짜장", "korean"),
    createMenu(46, "CU", "자이언트 떡볶이", "korean"),
    createMenu(47, "CU", "불닭볶음면 & 치즈", "korean"),
    createMenu(48, "노랑통닭", "알싸한 마늘 치킨", "chicken"),
    createMenu(49, "노랑통닭", "엄청 큰 후라이드", "chicken"),
    createMenu(50, "푸라닭", "고추마요 치킨", "chicken"),
    createMenu(51, "푸라닭", "콘소메이징", "chicken"),
    createMenu(52, "청년피자", "매드 쉬림프", "pizza"),
    createMenu(53, "청년피자", "할라불고기", "pizza"),
    createMenu(54, "피자에땅", "신세개 피자", "pizza"),
    createMenu(55, "땅스부대찌개", "테이크아웃 부대찌개", "stew"),
    createMenu(56, "명랑핫도그", "감자 통모짜 핫도그", "dessert"),
    createMenu(57, "명랑핫도그", "먹물 치즈 핫도그", "dessert"),
    createMenu(58, "설빙", "인절미 빙수", "dessert"),
    createMenu(59, "설빙", "애플망고 치즈 빙수", "dessert"),
    createMenu(60, "설빙", "초코 브라우니 빙수", "dessert"),
    createMenu(61, "베스킨라빈스", "파인트 아이스크림", "dessert"),
    createMenu(62, "베스킨라빈스", "쿼터 아이스크림", "dessert"),
    createMenu(63, "요거트월드", "요거트 아이스크림", "dessert"),
    createMenu(64, "와플대학", "애플 시나몬 와플", "dessert"),
    createMenu(65, "와플대학", "오레오 누텔라 와플", "dessert"),
    createMenu(66, "이디야", "꿀복숭아 플랫치노", "dessert"),
    createMenu(67, "맥도날드", "맥플러리", "dessert"),
    createMenu(68, "맥도날드", "상하이 치킨 스낵랩", "burger"),
    createMenu(69, "롯데리아", "양념감자", "burger"),
    createMenu(70, "롯데리아", "치즈스틱", "burger"),
    createMenu(71, "KFC", "닭껍질 튀김", "chicken"),
    createMenu(72, "KFC", "비스켓", "dessert"),
    createMenu(73, "던킨", "글레이즈드 도넛", "dessert"),
    createMenu(74, "던킨", "먼치킨 10개", "dessert"),
    createMenu(75, "크리스피크림", "오리지널 글레이즈드", "dessert"),
    createMenu(76, "써브웨이", "쿠키 세트", "dessert"),
    createMenu(77, "생활맥주", "앵그리 버드 치킨", "pub"),
    createMenu(78, "생활맥주", "수제맥주 샘플러", "pub"),
    createMenu(79, "금별맥주", "페스트리 피자", "pub"),
    createMenu(80, "금별맥주", "토마토 해장 파스탕", "pub"),
    createMenu(81, "인쌩맥주", "살얼음 맥주", "pub"),
    createMenu(82, "인쌩맥주", "김치전", "pub"),
    createMenu(83, "1943", "로제 파스타 치킨", "pub"),
    createMenu(84, "깡우동", "매운 우동", "pub"),
    createMenu(85, "깡우동", "탕수육", "pub"),
    createMenu(86, "노가리앤비어", "먹태 구이", "pub"),
    createMenu(87, "짝태와노가리", "짝태", "pub"),
    createMenu(88, "피쉬앤그릴", "모둠 오뎅탕", "pub"),
    createMenu(89, "와라와라", "과일주", "pub"),
    createMenu(90, "준코", "준코 라면", "pub"),
    createMenu(91, "뉴욕야시장", "핑거 스테이크", "pub"),
    createMenu(92, "뉴욕야시장", "맥앤치즈", "pub"),
    createMenu(93, "경성주막1929", "차돌 숙주 볶음", "pub"),
    createMenu(94, "지금보고싶다", "플레이트 I", "pub"),
    createMenu(95, "미술관", "통삼겹 볶음김치", "pub"),
    createMenu(96, "대동집", "녹두 김치 파전", "pub"),
    createMenu(97, "대동집", "멸치국수", "pub"),
    createMenu(98, "시장통닭", "가마솥 통닭", "chicken"),
    createMenu(99, "멕시칸치킨", "닭강정", "chicken"),
    createMenu(100, "림스치킨", "오리지널 치킨", "chicken"),
  ]
};
